# Generated by Django 5.0.2 on 2024-02-17 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_event_host'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='date',
        ),
    ]
